package ci.nsu.mobile.calculations.data.dao

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import ci.nsu.mobile.calculations.data.db.AppDatabase
import ci.nsu.mobile.calculations.data.entity.DepositEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

@RunWith(AndroidJUnit4::class)
class DepositDaoTest {

    private lateinit var db: AppDatabase
    private lateinit var dao: DepositDao

    private fun entity(
        id: Int = 0,          // 0 → auto-generate
        userId: Int = 1,
        startAmount: Double = 10_000.0,
        months: Int = 12,
        rate: Double = 10.0,
        monthlyTopUp: Double? = 500.0,
        finalAmount: Double = 25_000.0,
        profit: Double = 9_000.0,
        date: Long = System.currentTimeMillis()
    ) = DepositEntity(
        id = id,
        userId = userId,
        startAmount = startAmount,
        months = months,
        rate = rate,
        monthlyTopUp = monthlyTopUp,
        finalAmount = finalAmount,
        profit = profit,
        date = date
    )

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java).allowMainThreadQueries().build()
        dao = db.depositDao()
    }

    @After
    fun closeDb() {
        db.close()
    }

    @Test
    fun whenInsertThenDepositAppearsInUserFlow() = runBlocking {
        val e = entity(userId = 1)

        dao.insert(e)
        val list = dao.getByUser(1).first()

        assertEquals(1, list.size)
        assertEquals(e.startAmount, list[0].startAmount)
    }

    @Test
    fun whenInsertTwoDepositsForSameUserThenBothAreReturned() = runBlocking {
        dao.insert(entity(userId = 1, startAmount = 1_000.0))
        dao.insert(entity(userId = 1, startAmount = 2_000.0))
        val list = dao.getByUser(1).first()

        assertEquals(2, list.size)
    }

    @Test
    fun whenInsertThenAutoGeneratedIdIsNonZero() = runBlocking {
        dao.insert(entity())
        val inserted = dao.getByUser(1).first().first()

        assertTrue(inserted.id > 0)
    }

    @Test
    fun whenInsertDepositWithNullTopUpThenNullIsPersistedCorrectly() = runBlocking {
        dao.insert(entity(monthlyTopUp = null))
        val stored = dao.getByUser(1).first().first()

        assertNull(stored.monthlyTopUp)
    }

    @Test
    fun whenTwoUsersInsertThenEachGetOnlyOwnDeposits() = runBlocking {
        dao.insert(entity(userId = 1))
        dao.insert(entity(userId = 2))
        dao.insert(entity(userId = 2))

        val user1 = dao.getByUser(1).first()
        val user2 = dao.getByUser(2).first()

        assertEquals(1, user1.size)
        assertEquals(2, user2.size)
    }

    @Test
    fun whenNoDepositsInsertedThenFlowEmitsEmptyList() = runBlocking {
        val list = dao.getByUser(99).first()
        assertEquals(0, list.size)
    }

    @Test
    fun whenMultipleDepositsInsertedThenFlowReturnsMostRecentFirst() = runBlocking {
        dao.insert(entity(userId = 1, date = 1_000L))
        dao.insert(entity(userId = 1, date = 3_000L))
        dao.insert(entity(userId = 1, date = 2_000L))

        val list = dao.getByUser(1).first()

        assertEquals(3_000L, list[0].date)
        assertEquals(2_000L, list[1].date)
        assertEquals(1_000L, list[2].date)
    }

    @Test
    fun whenDeleteCalledThenDepositIsRemovedFromFlow() = runBlocking {
        dao.insert(entity(userId = 1))
        val inserted = dao.getByUser(1).first().first()

        dao.delete(inserted)
        val list = dao.getByUser(1).first()

        assertEquals(0, list.size)
    }

    @Test
    fun whenDeleteCalledThenOnlyTargetDepositIsRemoved() = runBlocking {
        dao.insert(entity(userId = 1, startAmount = 1_000.0))
        dao.insert(entity(userId = 1, startAmount = 2_000.0))
        val all = dao.getByUser(1).first()
        val toDelete = all.first { it.startAmount == 1_000.0 }

        dao.delete(toDelete)
        val remaining = dao.getByUser(1).first()

        assertEquals(1, remaining.size)
        assertEquals(2_000.0, remaining[0].startAmount)
    }

    @Test
    fun whenDeleteByIdCalledThenTargetRowIsRemoved() = runBlocking {
        dao.insert(entity(userId = 1))
        val id = dao.getByUser(1).first().first().id

        dao.deleteById(id)
        val list = dao.getByUser(1).first()

        assertEquals(0, list.size)
    }

    @Test
    fun whenDeleteByIdCalledWithNonExistentIdThenNoExceptionThrown() = runBlocking {
        dao.deleteById(99_999)

        assertEquals(0, dao.getByUser(1).first().size)
    }

    @Test
    fun whenDepositInsertedThenAllNumericFieldsArePersistedAccurately() = runBlocking {
        val e = entity(
            userId = 3,
            startAmount = 12_345.67,
            months = 18,
            rate = 7.5,
            monthlyTopUp = 1_111.11,
            finalAmount = 30_000.99,
            profit = 5_432.10,
            date = 98765L
        )
        dao.insert(e)

        val stored = dao.getByUser(3).first().first()

        assertEquals(e.startAmount, stored.startAmount, 0.001)
        assertEquals(e.rate, stored.rate, 0.001)
        assertEquals(e.monthlyTopUp, stored.monthlyTopUp)
        assertEquals(e.finalAmount, stored.finalAmount, 0.001)
        assertEquals(e.profit, stored.profit, 0.001)
        assertEquals(e.months, stored.months)
        assertEquals(e.date, stored.date)
    }
}